In [3]:
import numpy as np

In [8]:
a = np.array([[10,20,30,40], [50,60,70,80], [20,40,60,80]])
print(a)
type(a)

b = np.array([10,20,30,40])
print(b[0::2])

c = np.array([10,20,30,40])
print(c[1::2])

d = np.array([10,20,30,40])
print(d[::])


e = np.array([10,20,30,40])
print(e[::-1])

f = np.array([[10,20,30,40], [50,60,70,80]])
print(f[0:2,0:2])

g = np.array([[10,20,30,40], [50,60,70,80]])
print(g[0:2,0:3])

[[10 20 30 40]
 [50 60 70 80]
 [20 40 60 80]]
[10 30]
[20 40]
[10 20 30 40]
[40 30 20 10]
[[10 20]
 [50 60]]
[[10 20 30]
 [50 60 70]]


In [21]:
# To identify No of Rows and Columns 
g = np.array([[10,20,30,40], [50,60,70,80]])
print(g)
print("The number of Rows and Columns of the arrary g is: ",np.shape(g))


a = np.array([[10,20,30,40], [50,60,70,80], [20,40,60,80]])
print("The number of Rows and Columns of the arrary a is: ",np.shape(a))

print("Number of elements in the array a is: ", np.size(a))

print("Number of dimension (Rows & Columns) in the array a is: ", np.ndim(a))

print("Type of data type uesed is: ", a.dtype)

[[10 20 30 40]
 [50 60 70 80]]
The number of Rows and Columns of the arrary g is:  (2, 4)
The number of Rows and Columns of the arrary a is:  (3, 4)
Number of elements in the array a is:  12
Number of dimension (Rows & Columns) in the array a is:  2
Type of data type uesed is:  int64


2

In [24]:
g.shape # Array dimension Rows and Columns

(2, 4)

In [33]:
len(g) # Length of the Array

2

In [35]:
g.ndim # Number of array dimensions

2

In [31]:
g.size # Number of array elements

8

In [43]:
print(g.dtype) # Data type of array elements

int64


In [41]:
print(g.astype(float))

[[10. 20. 30. 40.]
 [50. 60. 70. 80.]]


In [56]:
print("Conversion of data type from int to string 'str' \n", a.astype(str))
b = a.astype(str)
print(a.dtype)
print(b.dtype)

Conversion of data type from int to string 'str' 
 [['10' '20' '30' '40']
 ['50' '60' '70' '80']
 ['20' '40' '60' '80']]
int64
<U21


In [49]:
print("data type of variable: ",type(g))
print("data type of array: ",a.dtype)

data type of variable:  <class 'numpy.ndarray'>
data type of array:  int64


In [9]:
g.shape

(2, 4)

In [28]:
import numpy as np
# Addition
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1 + arr2)
print(np.add(arr1,arr2))

[[60 60]
 [30 30]]
[[60 60]
 [30 30]]


In [29]:
# Subtraction
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])

print(np.subtract(arr1,arr2))

[[  0  20]
 [ 10 -10]]


In [32]:
# Multiplication
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])

print(arr1 * arr2)
print(np.multiply(arr1,arr2))

[[900 800]
 [200 200]]
[[900 800]
 [200 200]]


In [36]:
# Division

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])

print(arr1/arr2)
print(np.divide(arr1,arr2))

[[1.  2. ]
 [2.  0.5]]
[[1.  2. ]
 [2.  0.5]]


In [41]:
arr1 = ([2,3,4,5,6])
arr2 = ([2])

print("The square of number is",np.pow(arr1,arr2))

The square of number is [ 4  9 16 25 36]


In [50]:
arr1 = np.array([4,9,16,25,36])

print("The square root of the no is", np.sqrt(arr1))

The square root of the no is [2. 3. 4. 5. 6.]


In [52]:
arr1 = np.array([30,40,50])
arr2 = np.array([5,5,3])

print(np.concatenate([arr1,arr2]))

[30 40 50  5  5  3]
